codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 85%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target
    patch:
      default:
        target: 80%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
